name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feat'
  - title: '🐛 Hotfixes'
    label: 'fix'
  - title: '🔧 Refactors'
    label: 'refactor'
  - title: '📃 Docs'
    label: 'docs'
  - title: '📦 Chore'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # add '#' and '@' to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Describe changes
  
  $CHANGES
