name: Commerce

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  build:
    name: "[CI] Check Build/Testcases"
    runs-on: ubuntu-latest
    steps:
      - name: (Set Up) checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true

      - name: (Set Up) Set up Python for Documentation
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: (Set Up) Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: (Set Up) Grant Execute permission for gradlew
        run: chmod 777 gradlew

      - name: (Build) Build with Gradle
        run: ./gradlew clean build -i

      - name: (Test) Test Result
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: github.event_name == 'pull_request'
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: (Test) Test Failure Occurred Documentation.
        uses: mikepenz/action-junit-report@v3
        if: github.event_name == 'pull_request'
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}

      - name: (Test) Jacoco Coverage Report to PR
        id: jacoco
        if: github.event_name == 'pull_request'
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/build/JacocoReportDir/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: 📃Code Coverage Report
          update-comment: true
          pass-emoji: ':o:'
          fail-emoji: ':x:'

      - name: (Test) Coveralls Coverage Badge
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}

      - name: (Deploy) Copy the JAR file via the SSH server.
        id: copyjar
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          source: "build/libs/*.jar"
          target: "source"
          rm: true

      - name: (Deploy) Automated deployment
        id: deploy
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && steps.copyjar.outcome == 'success'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          username: ${{ secrets.DEPLOY_SSH_USERNAME }}
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          script: |
            SOURCE_DIR=source/build/libs
            FILE_NAME=`find $SOURCE_DIR/*SNAPSHOT.jar -printf "%f\n"`
            PID=$(lsof -i:8080 | awk '{print $2}' | grep -o '[0-9]*')
            
            if [ -z "$PID" ]; then
                    echo "#### THERE IS NO PROCESS ####"
            else
                    echo "#### KILL $PID ####"
                    sudo kill $PID
            fi
            echo "#### RUN $SOURCE_DIR/$FILE_NAME ####"
            sudo java -jar -Dspring.profiles.active=db $SOURCE_DIR/$FILE_NAME > /dev/null 2>&1 &


      - name: (Docs) Release Drafter
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && steps.deploy.outcome == 'success'
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci:
    name: "[CI] Check Convention"
    runs-on: ubuntu-latest
    steps:
      - name: (Set Up) checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
          submodules: true

      - name: (Set Up) Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: (Set Up) Grant Execute permission for gradlew
        run: chmod 777 gradlew

      - name: (Check) Check Convention Main Dir.
        run: ./gradlew checkstyleMain -i

      - name: (Check) Add Comment on PR when Check Result
        if: always()  # 항상 실행
        run: |
          if [ ${{ job.status }} == "success" ]; then
            MESSAGE="🙆 Great Checkstyle!"
          else
            MESSAGE="🙅 Checkstyle Exception!\nPlease fix the code style."
          fi

          echo '{"body": "'"$MESSAGE"'"}' > comment.json
          PR_NUMBER=$(curl -s -X GET -G -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" | jq -r ".[] | select(.head.ref == \"${{ github.head_ref }}\") | .number")
          echo "PR 번호: $PR_NUMBER"
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d @comment.json \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
